[package]
name = "near-ql-db"
version = "0.1.0"
edition = "2021"

[dependencies]
bigdecimal = "0.1"
diesel = { version = "1", features = ["numeric", "postgres", "r2d2"] }
diesel_migrations = "1"
near-lake-framework = "0.4"
r2d2 = "0.8"
thiserror = "1"
