[package]
name = "qlytics-graphql"
version = "0.1.0"
edition = "2021"

[dependencies]
base64 = "0.13"
chrono = "0.4"
graphql_client = "0.11"
hex = "0.4"
near-crypto = "0.14"
near-lake-framework = "0.5"
serde = "1"
serde_json = "1"
strum = "0.24"
strum_macros = "0.24"
